require 'fileutils'

platform :ios, '14.1'
plugin 'cocoapods-patch'
use_frameworks!

target 'Soundscape' do
    project 'GuideDogs.xcodeproj'
    
    # When `pod install` is called, the 'cocoapods-patch' plugin
    # will patches the pod with the diff file in `/patches`.
    pod "iOS-GPX-Framework", '0.0.2'
end

post_install do |installer|
    pods_root = File.join(__dir__, 'Pods')
    tbxml_header = Dir.glob(File.join(pods_root, 'TBXML', '**', 'TBXML.h')).first

    if tbxml_header
        %w[Public Private].each do |visibility|
            header_dir = File.join(pods_root, 'Headers', visibility, 'TBXML')
            FileUtils.mkdir_p(header_dir)
            FileUtils.cp(tbxml_header, File.join(header_dir, 'TBXML.h'))
        end
    end

    installer.pods_project.targets.each do |target|
        next unless target.name == 'iOS-GPX-Framework'

        target.build_configurations.each do |config|
            header_search_paths = Array(config.build_settings['HEADER_SEARCH_PATHS'])
            header_search_paths |= [
                '$(inherited)',
                '${PODS_ROOT}/Headers/Public/TBXML',
                '${PODS_ROOT}/Headers/Private/TBXML'
            ]
            config.build_settings['HEADER_SEARCH_PATHS'] = header_search_paths
        end
    end
end
