require 'fileutils'

platform :ios, '14.1'
plugin 'cocoapods-patch'
use_frameworks!

target 'Soundscape' do
    project 'GuideDogs.xcodeproj'
    
    # When `pod install` is called, the 'cocoapods-patch' plugin
    # will patches the pod with the diff file in `/patches`.
    pod "iOS-GPX-Framework", '0.0.2'
    pod "TBXML", '1.5'
end

post_install do |installer|
    pods_root = File.join(__dir__, 'Pods')
    tbxml_shim = File.join(pods_root, 'iOS-GPX-Framework', 'GPX', 'TBXML.h')
    minimum_ios_deployment_target = Gem::Version.new('12.0')

    unless File.exist?(tbxml_shim)
        File.write(tbxml_shim, <<~TBXML_HEADER)
            #import <Foundation/Foundation.h>

            typedef struct _TBXMLElement TBXMLElement;

            @interface TBXML : NSObject
            @property (nonatomic, assign, readonly) TBXMLElement *rootXMLElement;
            - (instancetype)initWithXMLString:(NSString *)aXMLString error:(NSError **)error;
            - (instancetype)initWithXMLData:(NSData *)data error:(NSError **)error;
            + (NSString *)valueOfAttributeNamed:(NSString *)name forElement:(TBXMLElement *)element;
            + (TBXMLElement *)childElementNamed:(NSString *)name parentElement:(TBXMLElement *)element;
            + (TBXMLElement *)nextSiblingNamed:(NSString *)name searchFromElement:(TBXMLElement *)element;
            + (NSString *)textForElement:(TBXMLElement *)element;
            @end
        TBXML_HEADER
        puts "Created TBXML shim header at #{tbxml_shim}"
    end

    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
            if deployment_target.nil? || Gem::Version.new(deployment_target) < minimum_ios_deployment_target
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_ios_deployment_target.to_s
            end

            next unless target.name == 'iOS-GPX-Framework'

            header_search_paths = Array(config.build_settings['HEADER_SEARCH_PATHS'])
            header_search_paths |= [
                '$(inherited)',
                '${PODS_ROOT}/Headers/Public/TBXML',
                '${PODS_ROOT}/Headers/Private/TBXML',
                '${PODS_ROOT}/iOS-GPX-Framework/GPX'
            ]
            config.build_settings['HEADER_SEARCH_PATHS'] = header_search_paths
        end
    end
end
